# Generated by Django 3.2.7 on 2021-11-30 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtranslation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Amino',
        ),
    ]
