# Generated by Django 2.2.7 on 2021-12-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtranslation', '0002_rename_question_amino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amino',
            name='amino_acid',
        ),
        migrations.RemoveField(
            model_name='amino',
            name='first_choice',
        ),
        migrations.RemoveField(
            model_name='amino',
            name='probability',
        ),
        migrations.RemoveField(
            model_name='amino',
            name='second_choice',
        ),
        migrations.AlterField(
            model_name='amino',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
